baseURL = "https://humansinc1.github.io/kosterblog"
title = "Блог Лосева"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-NXD4PJTV1J"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Блог Лосева"
description = "Личный блог Сергея Лосева"
keywords = [ "блог" ]
author = "Сергей Л"
images = "/assets/images/bonfire-1.jpg"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "/assets/images/bonfire.png"
  #favicon16x16 = "<link / abs url>"
  #favicon32x32 = "<link / abs url>"
  #apple_touch_icon = "<link / abs url>"
  #safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Главная"
  #icon = "images/bonfire.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Привет"
  Content = "Меня зовут Сергей Лосев и это мой блог"

  #[[params.socialIcons]]
  #name = "instagram"
  #url = "https://www.instagram.com/koster_podcast"

[params.analytics.google]
SiteVerificationTag = "G-NXD4PJTV1J"

#[params.analytics.bing]
#SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "93501423"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  #[params.editPost]
  #URL = "https://github.com/<path_to_repo>/content"
  #Text = "Suggest Changes"
  #appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

#[[menu.main]]
#identifier = "search"
#name = "Поиск"
#url = "search/"
#weight = 10

[[menu.main]]
identifier = "categories"
name = "Категории"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "about"
name = "Обо мне"
url = "about"
weight = 30

[[menu.main]]
identifier = "Archive"
name = "Архив"
url = "archive"
weight = 40

[markup.highlight]
noClasses = false

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
